#BSUB -J SCENIC
#BSUB -W 3:00 
#BSUB -o output
#BSUB -e logs
#BSUB -q short
#BSUB -n 28
#BSUB -M 256
#BSUB -R rusage[mem=256]
#BSUB -N
#BSUB -B
#BSUB -u dtruong4@mdanderson.org

var=`date +"%FORMAT_STRING"`
now=`date +"%m_%d_%Y"`
now=`date +"%Y-%m-%d"`

source ../.bashrc

#module load python/3.7.3-anaconda
conda activate r-arrow

conda_info=$(conda info)
echo "$conda_info"

R CMD BATCH scripts/LPS_SCENIC.r outs/LPS_SCENIC_${now}.out

echo "My job ran on the following host:"
hostname