#BSUB -J "velocyto" 
#BSUB -W 15:00 
#BSUB -o output 
#BSUB -e logs 
#BSUB -q medium 
#BSUB -n 6 
#BSUB -M 64 
#BSUB -R rusage[mem=64] 
#BSUB -N 
#BSUB -B 
#BSUB -env "all"
#BSUB -u dtruong4@mdanderson.org

#bash $HOME/LSF_scripts/scripts/samtools.sh $f

bash $HOME/LSF_scripts/scripts/velocyto.sh $f

echo "My R jobs are done."
date
echo "$f"
echo "My job ran on the following host:"
hostname